services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: DATABASE_URL
        sync: false